name = "langchain-worker"
main = "./.output/server/index.mjs"
compatibility_date = "2023-11-15"
compatibility_flags = [ "nodejs_compat" ]

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "langchain_js_nuxt"
